spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${DB_URL}?currentSchema=tournament_app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_versioned_data: true
      hibernate.format_sql: true
      hibernate.default_schema: tournament_app
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: tournament_app
    default-schema: tournament_app

pairing:
  algorithm:
    timeout-ms: 5000