DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'tournament_app'
          AND table_name = 'pairing_entity'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
ALTER TABLE tournament_app.pairing_entity
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
END IF;
END $$;
